### ISSUE TITLE
Security Alert: API Keys Exposed in Your Code

### ISSUE THREAD

**Issue by godilman** [saha-sagnik/Mental-Health#1]
Hello,

I hope this message finds you well. I was browsing through GitHub and noticed that your repository contains API keys committed directly in the code. I wanted to kindly bring this to your attention because exposing API keys publicly can pose a significant security risk to your application and associated services.

Here are a few steps you might consider to resolve this issue:

Remove the API Keys: Consider using git rm to remove the files containing the API keys from your repository. Don't forget to push the changes.
Use Environment Variables: Instead of hardcoding API keys in your code, you can store them in environment variables. This way, your keys remain off the source code and can be different across your development, staging, and production environments.
Reset the Exposed Keys: It's advisable to regenerate any keys that were exposed publicly to prevent unauthorized use.
.gitignore: For future prevention, you can add sensitive files or file patterns containing keys to a .gitignore file to avoid accidentally committing them.
GitHub provides a helpful guide on removing sensitive data from a repository, which you might find useful: https://docs.github.com/en/github/authenticating-to-github/removing-sensitive-data-from-a-repository.

Please understand my intention is solely to help you protect your project and keep it secure. If you have any questions or need further assistance, feel free to ask.

**Comment by ShadowSlayer03** [comment]
Hello Sir, 
Thank you so much for the concern. Actually we had made separate .env files for storing these but since the project is still in development, and multiple people are making changes to it, we hadn't added them to the .gitignore so that everyone still has access to the .env being changed.
I know it is not a good idea to expose these details and surely we'll be rectifying in the next commit.
I shall consider the issue closed.
Thanks once again hope you have a nice day.
